<a href="https://colab.research.google.com/github/FerdiErs/NGC-Hacktiv8/blob/main/h8dsft_Linear_Algebra1_NGC_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
from numpy import array

In [3]:
### Membuat Tensor 

T = array([
          [[23,50],[7,12]],
          [[75,21],[57,12]],
          [[57,67],[99,43]],
          [[87,26],[18,84]],
           ])
print(T)

[[[23 50]
  [ 7 12]]

 [[75 21]
  [57 12]]

 [[57 67]
  [99 43]]

 [[87 26]
  [18 84]]]


In [6]:
### mendefinisikan matrix 

A = np.array([
            [23,50,19],
            [7,12,109],
            [57,67,98]
            ])
B = np.array([17,22,19])

print(A)
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[17 22 19]


In [19]:
### Perkalian Matrix A dan Matrix B
Hasil = A @ B 
print('Hasil perkalian matrix a dan matrix b : \n', Hasil)

Hasil perkalian matrix a dan matrix b : 
 [1852 2454 4305]


In [10]:
A = [[23,50,19],
     [7,12,109],
     [57,67,98]]

matrix_A = np.array(A)
matrix_A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [14]:
### Transpose Matrix_A
Transpose_Matrix_A = matrix_A.T 

print('Hasil Transpose dari Matrix_A:\n',Transpose_Matrix_A)

Hasil Transpose dari Matrix_A:
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [15]:
### Determinan matrix_A
det_a = np.linalg.det(matrix_A)
print('Hasil determinan dari matrix a : \n', det_a)

Hasil determinan dari matrix a : 
 131344.0000000002


In [16]:
### inverse dari matrix_A 
inv_a = np.linalg.inv(matrix_A)
print('Hasil Inverse dari matrix a :\n', inv_a)

Hasil Inverse dari matrix a :
 [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]


In [17]:
print(matrix_A @ inv_a)

[[1.00000000e+00 1.90819582e-17 1.32923186e-16]
 [7.22078647e-17 1.00000000e+00 5.44269491e-17]
 [6.73506390e-16 1.97758476e-16 1.00000000e+00]]


In [18]:
# Pembuktian Matrix Identitas

print(matrix_A)
print('')

matrix_I = np.eye(3, 3)
print(matrix_I)
print('')

print(matrix_A @ matrix_I)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 23.  50.  19.]
 [  7.  12. 109.]
 [ 57.  67.  98.]]
